In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Lr_religion_dataset_rt_new.csv")
data

,Unnamed: 0,tweet,label,predicted
0,0,i would rather stand with god and be judged by...,6,6
1,1,youve got voices pulling you in all different ...,6,2
2,2,lord we need a generation of believers who are...,6,6
3,3,what are you living for i resolve to give god...,6,6
4,4,when all you see is your pain you lose sight ...,6,2
...,...,...,...,...
72,72,gentlemen you can not fight in here this is ...,2,2
73,73,i do not want to survive i want to live,2,2
74,74,elementary my dear watson,2,2
75,75,that will do pig that will do,2,2
76,76,i wish i knew how to quit you,2,2

In [3]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)

In [4]:
mask=data.label!=data.predicted

In [5]:
data[mask]

                                                tweet  label  predicted
1   youve got voices pulling you in all different ...      6          2
4   when all you see is your pain  you lose sight ...      6          2
10  there is a god who knows exactly what youre worth      6          2
12                     faith is the only true shelter      6          7
16   show me a catholic  and i will show you a junkie      6          2
17  i was born a catholic and now i am a lapsed ca...      6          2
19  life is precious  especially if you are a chri...      6          2
20                         we bet that there is a god      6          2
21  do you think people like the christians hire u...      6          2
22                                        ohh jesus        6          2
23                                 holy fucking jesus      6          2
35  hatred is never appeased by hatred in this wor...      7          2
39  if a man going down into a river  swollen and ...      7          2
45  all tremble at violence  all fear death  putti...      7          6
46  they blame those who remain silent  they blame...      7          2
49  as an elephant in the battlefield withstands a...      7          6
55  if you let my daughter go now  that will be th...      2          6
64                    it was beauty killed the beast       2          6

In [7]:
data[mask].to_csv("wrong_predicted_lr.csv")

In [8]:
data=pd.read_csv("SVC_religion_dataset_rt_new.csv")
data

,Unnamed: 0,tweet,label,predicted
0,0,i would rather stand with god and be judged by...,6,6
1,1,youve got voices pulling you in all different ...,6,2
2,2,lord we need a generation of believers who are...,6,6
3,3,what are you living for i resolve to give god...,6,6
4,4,when all you see is your pain you lose sight ...,6,2
...,...,...,...,...
72,72,gentlemen you can not fight in here this is ...,2,2
73,73,i do not want to survive i want to live,2,2
74,74,elementary my dear watson,2,2
75,75,that will do pig that will do,2,2
76,76,i wish i knew how to quit you,2,2

In [9]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)

In [10]:
mask=data.label!=data.predicted

In [11]:
data[mask].to_csv("wrong_predicted_SVC.csv")

In [12]:
data=pd.read_csv("Lr_religious_or_not.csv")
data.drop(['Unnamed: 0'],axis=1,inplace=True)
mask=data.label!=data.predicted
data[mask].to_csv("wrong_predicted_LR_religious_or_not.csv")

In [13]:
data=pd.read_csv("SVC_religious_or_not.csv")
data.drop(['Unnamed: 0'],axis=1,inplace=True)
mask=data.label!=data.predicted
data[mask].to_csv("wrong_predicted_SVC_religious_or_not.csv")